name: flicky
description: Мобильное приложение для поиска случайных фильмов
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # HTTP запросы
  http: ^1.1.0
  
  # Работа с .env файлами
  flutter_dotenv: ^5.1.0
  
  # URL launcher для открытия стриминговых сервисов
  url_launcher: ^6.2.2
  
  # Кэширование изображений
  cached_network_image: ^3.3.1
  
  # Material icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - .env

flutter_launcher_icons:
  image_path: "assets/logo/logo.png"
  android: true
  ios: false
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    favicon: true
  macos:
    generate: false
  windows:
    generate: false
  linux:
    generate: false
